---
sidebar: sidebar
api: true
explorer: false
permalink: 'cbs/delete-account-providers-cloudmanager_cbs-api-v1-backup-working-environment-volume-snapshot.html'
summary: 'Delete all snapshots (volume)'
---

= Delete all snapshots (volume)
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-delete]#DELETE# [.api-doc-code-block]#`/account/{accountId}/providers/cloudmanager_cbs/api/v1/backup/working-environment/{workingEnvironmentId}/volume/{volumeId}/snapshot`#



Deletes all the snapshots for a specified volume backed up by using the NetApp Backup and Recovery service for a system.

*Token usage:* NetApp Console user token.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|force
|boolean
|query
|False
a|If set to true, all the metadata for the snapshots is cleaned from the database. Check if the snapshots are in the object store and then clean them.


|remove-object-store-config
|boolean
|query
|False
a|If set to true, the object store configuration that is not being used by any volume is cleaned up from the system.


|accountId
|string
|path
|True
a|Account ID


|workingEnvironmentId
|string
|path
|True
a|System ID


|volumeId
|string
|path
|True
a|File system or volume ID


|authorization
|string
|header
|True
a|User token


|X-Agent-Id
|string
|header
|True
a|Request identifier


|===

== Response

```
Status: 202, Default response
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|job-id
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job-id": "string"
}
====

