---
sidebar: sidebar
api: true
explorer: false
permalink: 'cbs/get-account-providers-cloudmanager_cbs-api-v1-backup-working-environment-volume-snapshot-.html'
summary: 'Retrieve specific snapshot information for a volume'
---

= Retrieve specific snapshot information for a volume

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/account/{accountId}/providers/cloudmanager_cbs/api/v1/backup/working-environment/{workingEnvironmentId}/volume/{volumeId}/snapshot/{snapshotId}`#



Retrieves information of a particular snapshot for a specified volume backed up by using the NetApp Backup and Recovery service for a system. This API endpoint retrieves the details of the volume snapshots from the NetApp Console SaaS application. It retrieves the snapshot name, snapshot creation time, archive status, and size. It also retrieves the object-lock, ransomware-scan-status-failure, and ransomware-scan-status.

**Token usage:** NetApp Console user token.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|accountId
|string
|path
|True
a|

|workingEnvironmentId
|string
|path
|True
a|

|volumeId
|string
|path
|True
a|

|snapshotId
|string
|path
|True
a|

|authorization
|string
|header
|True
a|

|X-Agent-Id
|string
|header
|True
a|
|===

== Response

```
Status: 200, Default response
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|id
|string
|False
a|

|name
|string
|False
a|

|creation-time
|number
|False
a|

|archived
|boolean
|False
a|

|size
|number
|False
a|

|last-ransomware-scan
|number
|False
a|

|object-lock
|string
|False
a|

|ransomware-scan-status-failure
|string
|False
a|

|ransomware-scan-status
|string
|False
a|

|volume-id
|string
|False
a|

|volume-name
|string
|False
a|

|working-environment-id
|string
|False
a|

|working-environment-name
|string
|False
a|

|svm
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "id": "string",
  "name": "string",
  "object-lock": "string",
  "ransomware-scan-status-failure": "string",
  "ransomware-scan-status": "string",
  "volume-id": "string",
  "volume-name": "string",
  "working-environment-id": "string",
  "working-environment-name": "string",
  "svm": "string"
}
====

