---
sidebar: sidebar
api: true
explorer: false
permalink: 'cbs/get-account-providers-cloudmanager_cbs-api-v1-working-environment-volume-snapshot.html'
summary: 'Retrieve a list of snapshot details for a volume'
---

= Retrieve a list of snapshot details for a volume
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/account/{accountId}/providers/cloudmanager_cbs/api/v1/working-environment/{workingEnvironmentId}/volume/{volumeId}/snapshot`#



Retrieves a list of snapshot details pertaining to a specific volume in a particular system. The system ID, volume ID, and snapshot ID are passed as parameters for the REST API call. You can query by passing parameters to specify the maximum number of records that should be returned, the next subsequent snapshot UUID to get results from, and the next `CP-COUNT` from where the results should be fetched.

*Token usage:* NetApp Console user token.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|max-records
|number
|query
|False
a|Maximum records to return


|cursor
|string
|query
|False
a|Next snapshot UUID to get results from


|cp-count
|number
|query
|False
a|Next CP count to get results from


|include-indexing-status
|boolean
|query
|False
a|Include the field named indexing-status on each snapshot in the response


|accountId
|string
|path
|True
a|Account ID


|workingEnvironmentId
|string
|path
|True
a|System ID


|volumeId
|string
|path
|True
a|Volume ID


|authorization
|string
|header
|True
a|User token


|X-Agent-Id
|string
|header
|True
a|Request identifier


|===

== Response

```
Status: 200, Default response
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|snapshot
|array[link:#snapshot[snapshot]]
|False
a|

|num-records
|number
|False
a|

|cursor
|string
|False
a|

|cp-count
|number
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "snapshot": [
    {
      "id": "string",
      "name": "string",
      "indexing-status": "string"
    }
  ],
  "cursor": "string"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#snapshot]
[.api-collapsible-fifth-title]
snapshot

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|id
|string
|False
a|

|name
|string
|False
a|

|size
|number
|False
a|

|creation-time
|number
|False
a|

|indexing-status
|string
|False
a|Whether the snapshot has been indexed by the Indexed Catalog. Returned only for catalogs running version 2 indexing, and only when the name of the volume is known. A snapshot the catalog does not account for, including when the catalog cannot be reached, is reported as NOT_INDEXED.


|===


//end collapsible .Definitions block
====
