---
sidebar: sidebar
api: true
explorer: false
permalink: 'cbs/get-account-providers-cloudmanager_cbs-api-v1-license-working-environment-.html'
summary: 'Retrieve license validity'
---

= Retrieve license validity

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/account/{accountId}/providers/cloudmanager_cbs/api/v1/license/working-environment/{workingEnvironmentId}`#



Retrieves the license validity of the systems from the NetApp Console SaaS application. The API retrieves the eligibility of the current license used and it also returns the days remaining if you are using a trial license.

**Token usage:** NetApp Console user token.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|provider
|string
|query
|True
a|* enum: ["AWS", "AZURE", "GCP", "SGWS"]


|cloudProviderAccountId
|string
|query
|False
a|Cloud provider account ID. AWS account ID/Azure subscription ID/ Google Cloud project ID. It is not mandatory to send this query parameter for StorageGRID.


|accountId
|string
|path
|True
a|Account ID


|workingEnvironmentId
|string
|path
|True
a|System ID


|authorization
|string
|header
|True
a|User token


|X-Agent-Id
|string
|header
|True
a|Request identifier

|===

== Response

```
Status: 200, Default response
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|free-trial-end
|number
|False
a|

|eligible
|boolean
|False
a|

|===


