---
sidebar: sidebar
api: true
explorer: false
permalink: 'cbs/overview.html'
summary: 'NetApp Backup and Recovery REST API'
---

= NetApp Backup and Recovery REST API
:imagesdir: ../media/



Backup and Recovery through the NetApp Console provides backup and restore for protection and long-term archiving of data residing in Cloud Volumes ONTAP and on-premises ONTAP clusters (AFF/FAS/OTS). You can generate and store backups in an object store and restore data any time and to any location.

The following components are defined within Backup and Recovery:

* SFR
* Backup
* Restore
* System
* Cloud
* Job
* Catalog
* License
* Ransomware Scan
* Panoramic Protection
* Replication
* Report
* StorageGRID

NOTE: Before using the API reference documentation, review the
https://docs.netapp.com/us-en/console-automation/platform/overview.html[Get started] section for the
Console APIs. For more information about the security tokens and identifiers you'll need when using the API, review the
https://docs.netapp.com/us-en/console-automation/platform/get_identifiers.html[Common workflows and tasks] section.

'''

== REST implementation

=== HTTP methods

|===
| Method | Description

| POST
| Create an object instance

| GET
| Retrieve an object instance or collection

| PATCH
| Update an existing object

| DELETE
| Remove an existing object
|===

=== Request headers

|===
| Request Header | Description

| Authorization
| This header contains a bearer token used to access the Console server.

| X-Agent-Id
| Required. Contains the Console agent ID.

| Content-Type
| This representation header is used to indicate the original media type of the resource.

| Accept
| The server automatically returns content in JSON format if Accept header is not specified.
|===

=== Response headers

This API uses the standard HTTP response headers common with all Console APIs. See
https://docs.netapp.com/us-en/bluexp-automation/platform/http_details.html[REST implementation] for more information.

=== HTTP status codes

|===
| HTTP Status Code | Description

| 200
| OK: Returned for successful operation completion

| 202
| Accepted: The request was accepted and is currently in process.

| 204
| The operation was completed successfully and the server did not send a response message.

| 400
| Bad Request: Returned if the input is malformed and could not be parsed.

| 401
| Unauthorized: Returned if user authentication failed or the token has expired.

| 403
| Forbidden: Returned for authorization errors depending on the resource and token.

| 5xx
| An unexpected error occurred within the Console server which has prevented it from fulfilling the request.
|===

== Error handling

There are two processes involved with error handling and processing:

* The error is logged for supportability
* The error is also returned to the caller for any specific handling


