---
sidebar: sidebar
api: true
explorer: false
permalink: 'cbs/panoramic_protection_overview.html'
summary: 'Panoramic protection endpoints in the NetApp Backup and Recovery REST API'
---

= Panoramic protection endpoints in the NetApp Backup and Recovery REST API



The Panoramic Protection API enables you to automate the complete 3-2-1 backup spectrum using a single control plane to simplify your implementation of the various components of 3-2-1 model where they are needed, without using multiple resource managers and assistance from specially trained personnel. You can configure backups either in a cascading workflow or fan-out workflow. You can perform the following operations by using the Panoramic Protection endpoints:

* Enable 3-2-1 backup on systems by creating the required cluster-peering for replication and the required object-store buckets for backup to cloud in cascading or fan-out topologies. +

* Modify 3-2-1 backup on systems by configuring the setup required for replication or backup to cloud, to create cascading or fan-out topologies. +

* Create 3-2-1 cascading or fan-out backup topologies by configuring volume replication and backup to cloud relationship. +

* Modify or add 3-2-1 backup on volumes by configuring replication or backup to cloud, to create cascading or fan-out topologies.


