---
sidebar: sidebar
api: true
explorer: false
permalink: 'cbs/post-account-providers-cloudmanager_cbs-api-v3-restore.html'
summary: 'Perform a volume, file, and folder-level restore operation (v3)'
---

= Perform a volume, file, and folder-level restore operation (v3)

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/account/{accountId}/providers/cloudmanager_cbs/api/v3/restore`#



Performs a volume, file, and folder-level restore (version 3) operation. It is also possible to do a multi-level or nested-level folder restore operation. This API validates whether a backup of a volume exists. The restore operation is not supported on data protection volumes, a target volume with a different language code than the source volume, volumes with a size of less than 1GB, and volumes enabled with a SnapLock license (WORM license). In addition, restoring both files and folders is not supported. Restoring multiple folders is also not supported. The API checks whether the source and target cloud providers match and also verifies whether the backup and restore operation is supported in the system.

If DataLock and ransomware protection is enabled on a system, a ransomware scan is performed on the specified cloud backup related to the volume that is to be restored. To skip the scan, set the "skip-ransomware-check" parameter to "true".

To indicate that the volume restore is part of an application restore workflow, set the "is-app-volume-restore" parameter to "true". This disables certain steps such as mounting the volume after the storage volume restore.

This version adds support for accepting a list of target aggregates.

**Token usage:** NetApp Console user token.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|accountId
|string
|path
|True
a|Account ID


|authorization
|string
|header
|True
a|User token


|X-Agent-Id
|string
|header
|True
a|Request identifier

|===

== Request Body

                

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|restore
|link:#restore[restore]
|True
a|

|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "restore": {
    "type": "string",
    "restore-source": "string",
    "archive-restore-priority": "string",
    "source": {
      "working-environment-id": "string",
      "working-environment-name": "string",
      "bucket": "string",
      "volume-name": "string",
      "volume-id": "string",
      "snapshot": "string"
    },
    "target": {
      "working-environment-id": "string",
      "working-environment-name": "string",
      "svm": "string",
      "volume-name": "string",
      "path": "string",
      "aggregates": [
        "string"
      ]
    },
    "file": [
      {}
    ]
  }
}
====

== Response

```
Status: 202, Default response
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|job-id
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job-id": "string"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#source]
[.api-collapsible-fifth-title]
source

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|working-environment-id
|string
|True
a|

|working-environment-name
|string
|True
a|

|bucket
|string
|True
a|

|volume-name
|string
|True
a|

|volume-id
|string
|True
a|

|snapshot
|string
|True
a|

|===


[#target]
[.api-collapsible-fifth-title]
target

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|working-environment-id
|string
|True
a|

|working-environment-name
|string
|True
a|

|svm
|string
|True
a|

|volume-name
|string
|True
a|

|path
|string
|False
a|

|retain-source-path
|boolean
|False
a|

|aggregates
|array[string]
|False
a|

|===


[#file]
[.api-collapsible-fifth-title]
file

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|inode
|string
|True
a|

|path
|string
|True
a|

|type
|string
|True
a|

|size
|number
|True
a|

|mtime
|number
|True
a|

|source-file-path
|string
|False
a|

|===


[#restore]
[.api-collapsible-fifth-title]
restore

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|restore-source
|string
|False
a|Specifies the source of the restore


|restore-to-replication-source
|boolean
|False
a|

|archive-restore-priority
|string
|False
a|Required to specify the archival retrieval priority to determine the restoration time


|source
|link:#source[source]
|True
a|

|target
|link:#target[target]
|True
a|

|file
|array[link:#file[file]]
|False
a|

|skip-ransomware-check
|boolean
|False
a|Skips a ransomware scan


|skip-file-rename
|boolean
|False
a|Skips file rename during the restore


|is-on-demand-restore
|boolean
|False
a|Triggers an on-demand restore


|is-app-volume-restore
|boolean
|False
a|Indicates that the volume restore is part of an application restore workflow


|skip-azure-private-endpoint-creation
|boolean
|False
a|Optional input field to skip private endpoint creation for Azure


|===


[#body]
[.api-collapsible-fifth-title]
body

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|restore
|link:#restore[restore]
|True
a|

|===


//end collapsible .Definitions block
====
