---
sidebar: sidebar
api: true
explorer: false
permalink: 'cbs/post-account-providers-cloudmanager_cbs-api-v1-working-environment-backup-policy.html'
summary: 'Create a backup policy'
---

= Create a backup policy

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/account/{accountId}/providers/cloudmanager_cbs/api/v1/working-environment/{workingEnvironmentId}/backup-policy`#



Creates a backup policy in a system. The number of retained backups can be up to a maximum of 1018 when no backup policies are assigned to a volume. You can edit a policy to create up to 4000 backups after you assign volumes to a policy through ONTAP CLI. This API endpoint validates whether the ONTAP version used by a system supports archiving. You can archive the backups to a cloud archive tier by setting the archive-after-days in the policy. You can archive to AWS Glacier, Deep Glacier, Azure Archive, and Google Archive.

You can enable DataLock and Ransomware protection beginning with ONTAP 9.11.1 and later (supported for AWS, Azure, and StorageGRID). This is applicable only for new backup activation. Interoperability with archival policy is not supported. For AWS, DataLock and Ransomware Protection can be enabled in the "GOVERNANCE" mode or "COMPLIANCE" mode. For Azure, DataLock and Ransomware Protection can be enabled in the "UNLOCKED" mode or "LOCKED" mode.

**Token usage:** NetApp Console user token.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|accountId
|string
|path
|True
a|Account ID


|workingEnvironmentId
|string
|path
|True
a|System ID


|authorization
|string
|header
|True
a|User token


|X-Agent-Id
|string
|header
|True
a|Request identifier

|===

== Request Body

                

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|False
a|

|rule
|array[link:#rule[rule]]
|True
a|

|transfer-schedule
|string
|False
a|

|sgws-archival
|link:#sgws-archival[sgws-archival]
|False
a|

|archive-after-days
|string
|False
a|

|provider
|string
|False
a|* enum: ["AWS", "AZURE", "GCP", "SGWS", "ONTAP_S3"]


|object-lock
|string
|False
a|

|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "name": "string",
  "rule": [
    {
      "label": "string",
      "retention": "string",
      "period": "string"
    }
  ],
  "transfer-schedule": "string",
  "sgws-archival": {
    "cloud-storage-pool": {
      "provider": "string",
      "provider-account-id": "string",
      "region": "string",
      "access-key": "string",
      "secret-password": "string",
      "archive-storage-class": "string"
    }
  },
  "archive-after-days": "string",
  "provider": "string",
  "object-lock": "string"
}
====

== Response

```
Status: 200, Default response
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "name": "string"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#rule]
[.api-collapsible-fifth-title]
rule

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|label
|string
|False
a|

|retention
|string
|False
a|

|period
|string
|False
a|

|===


[#cloud-storage-pool]
[.api-collapsible-fifth-title]
cloud-storage-pool

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|provider
|string
|True
a|Cloud provider where the cloud storage pool is hosted


|provider-account-id
|string
|True
a|Cloud provider account ID where the cloud storage pool is hosted


|region
|string
|True
a|Cloud provider region where the cloud storage pool is hosted


|access-key
|string
|False
a|Required input field if the provider is AWS


|secret-password
|string
|False
a|Required input field if the provider is AWS


|archive-storage-class
|string
|False
a|Required for AWS to specify which storage class to use for archiving


|===


[#sgws-archival]
[.api-collapsible-fifth-title]
sgws-archival

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|cloud-storage-pool
|link:#cloud-storage-pool[cloud-storage-pool]
|False
a|

|===


[#body]
[.api-collapsible-fifth-title]
body

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|False
a|

|rule
|array[link:#rule[rule]]
|True
a|

|transfer-schedule
|string
|False
a|

|sgws-archival
|link:#sgws-archival[sgws-archival]
|False
a|

|archive-after-days
|string
|False
a|

|provider
|string
|False
a|* enum: ["AWS", "AZURE", "GCP", "SGWS", "ONTAP_S3"]


|object-lock
|string
|False
a|

|===


//end collapsible .Definitions block
====
