---
sidebar: sidebar
api: true
explorer: false
permalink: 'cbs/post-account-providers-cloudmanager_cbs-api-v3-backup-working-environment-volume-.html'
summary: 'Enable backup for a volume (v3)'
---

= Enable backup for a volume (v3)
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/account/{accountId}/providers/cloudmanager_cbs/api/v3/backup/working-environment/{workingEnvironmentId}/volume/{volumeId}`#



Enables backup for a specified volume (version V3). This version
of the endpoint runs the job asynchronously. Backup is not allowed
for a volume enabled with a SnapLock license (WORM license). You can
configure the different backup modes. The AD_HOC mode creates an
on-demand snapshot and stores a backup on the respective cloud.
SCHEDULED mode (default mode) creates snapshots according to the ONTAP
snapshot policy and stores a backup on the cloud according to the backup
policy. Based on the defined backup policy, this API endpoint creates a
SnapMirror to cloud relationship with a specific cloud object storage
system. You can use this endpoint to set the archive after days
parameter to move the volume data to the archive tier and also enable the
object lock and ransomware detection feature on the volume.

*Token usage:* NetApp Console user token.

NOTE: NetApp recommends that you use this endpoint for on-demand
(AD_HOC) backups of a volume. To enable backup on volumes, including for
multi-bucket or per-volume object storage configurations, use the https://docs.netapp.com/us-en/console-automation/cbs/post-account-providers-cloudmanager_cbs-api-v2-panoramic-protection-working-environment-volume.html[v2
panoramic protection API].


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|accountId
|string
|path
|True
a|Account ID


|workingEnvironmentId
|string
|path
|True
a|System ID


|volumeId
|string
|path
|True
a|Volume ID


|authorization
|string
|header
|True
a|User token


|X-Agent-Id
|string
|header
|True
a|Request identifier


|===

== Request Body

                   

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|mode
|string
|False
a|AD_HOC mode creates an on-demand snapshot and backs it up on the respective cloud. SCHEDULED mode creates snapshots as per the ONTAP snapshot policy and backs it up to the cloud as per the backup policy. [Deprecated] IMMEDIATE mode is designed for internal use cases and cannot be used for newer integrations

* enum: ["AD_HOC", "SCHEDULED", "IMMEDIATE"]


|adhoc-backup-details
|link:#adhoc-backup-details[adhoc-backup-details]
|False
a|

|backup-policy
|link:#backup-policy[backup-policy]
|False
a|

|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "mode": "string",
  "adhoc-backup-details": {
    "name": "string",
    "snapmirrorLabel": "string"
  },
  "backup-policy": {
    "name": "string",
    "rule": [
      {
        "label": "string",
        "retention": "string"
      }
    ],
    "archive-after-days": "string",
    "object-lock": "string"
  }
}
====

== Response

```
Status: 202, Default response
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|job-id
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job-id": "string"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#adhoc-backup-details]
[.api-collapsible-fifth-title]
adhoc-backup-details

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|False
a|

|snapmirrorLabel
|string
|False
a|

|===


[#rule]
[.api-collapsible-fifth-title]
rule

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|label
|string
|False
a|

|retention
|string
|False
a|

|===


[#backup-policy]
[.api-collapsible-fifth-title]
backup-policy

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|False
a|Required input


|rule
|array[link:#rule[rule]]
|False
a|

|archive-after-days
|string
|False
a|

|object-lock
|string
|False
a|

|===


//end collapsible .Definitions block
====
