---
sidebar: sidebar
api: true
explorer: false
permalink: 'cbs/post-account-providers-cloudmanager_cbs-api-v2-panoramic-protection-working-environment-volume.html'
summary: 'Enable comprehensive panoramic protection for multiple volumes (v2)'
---

= Enable comprehensive panoramic protection for multiple volumes (v2)
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/account/{accountId}/providers/cloudmanager_cbs/api/v2/panoramic-protection/working-environment/{workingEnvironmentId}/volume`#



Enables comprehensive panoramic protection for multiple volumes. Based on the selected topology (cascading or fan-out), the API creates a replication relationship to the secondary cluster and a backup-to-cloud relationship to a cloud or StorageGRID object store. During replication setup, the API verifies cluster peering between the primary and secondary clusters and, if missing, creates cluster peering, SVM peering, and a DP volume on the secondary cluster. The API then runs SnapMirror create and initialize operations. For backup to cloud, the API creates a bucket and then creates and initializes the SnapMirror Cloud relationship.

*Token usage:* NetApp Console user token.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|accountId
|string
|path
|True
a|Account ID


|workingEnvironmentId
|string
|path
|True
a|System ID


|authorization
|string
|header
|True
a|Authorization token


|X-Agent-Id
|string
|header
|True
a|Agent ID


|===

== Request Body

                   

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|auto-backup-enabled
|boolean
|False
a|Automatically back up all volumes in the system


|max-transfer-rate
|number
|False
a|Modifies node-level throttling of an ONTAP cluster. Value to be specified in kilo bytes per second (kbps). A value of 0 implies unlimited throttling.


|export-existing-snapshots
|boolean
|False
a|Export pre-existing snapshots to object storage


|fix-mismatch-labels
|boolean
|False
a|

|skip-discovery
|boolean
|False
a|Skip discovery as part of backup activation. Default value is false.


|skip-workload-validation
|boolean
|False
a|Skip workload validation during panoramic protection activation for volumes


|volumes
|array[link:#volumes[volumes]]
|True
a|

|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "volumes": [
    {
      "volume-id": "string",
      "volume-name": "string",
      "source-snapshot": "string",
      "architecture": "string",
      "workload": "string",
      "mode": "string",
      "type": "string",
      "backup-policy": {
        "name": "string",
        "rule": [
          {
            "label": "string",
            "retention": "string"
          }
        ],
        "archive-after-days": "string",
        "object-lock": "string",
        "sgws-archival": {
          "cloud-storage-pool": {
            "provider": "string",
            "provider-account-id": "string",
            "region": "string",
            "archive-storage-class": "string",
            "resource-group": "string"
          }
        }
      },
      "snapshot-policy": "string",
      "replication": {
        "working-environment-id": "string",
        "working-environment-name": "string",
        "svm": "string",
        "policy-name": "string",
        "prefix": "string",
        "suffix": "string",
        "destination-aggregates": [
          "string"
        ]
      },
      "is-enabled": {
        "local-snapshot": false,
        "replication": false,
        "cloud-backup": false
      },
      "object-storage-details": [
        {
          "object-storage-name": "string",
          "provider": "string",
          "region": "string",
          "ip-space": "string",
          "aws": {
            "account-id": "string",
            "kms-key-id": "string",
            "private-endpoint": {
              "id": "string"
            },
            "archive-storage-class": "string"
          },
          "azure": {
            "resource-group": "string",
            "storage-account": "string",
            "subscription": "string",
            "private-endpoint": {
              "subnet": "string"
            },
            "key-vault": {
              "key-vault-id": "string",
              "key-name": "string"
            }
          },
          "gcp": {
            "project-id": "string",
            "access-key": "string",
            "secret-password": "string",
            "credentials-id": "string",
            "kms": {
              "key-ring-id": "string",
              "crypto-key-id": "string"
            }
          },
          "sgws": {
            "storage-grid-id": "string",
            "storage-server-name": "string",
            "storage-server": "string",
            "access-key": "string",
            "secret-password": "string",
            "credential-id": "string"
          },
          "ontap-s3": {
            "storage-server": "string",
            "access-key": "string",
            "secret-password": "string",
            "credential-id": "string"
          },
          "s3-compatible": {
            "storage-server": "string",
            "access-key": "string",
            "secret-password": "string"
          }
        }
      ]
    }
  ]
}
====

== Response

```
Status: 202, Default response
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|job-id
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job-id": "string"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#rule]
[.api-collapsible-fifth-title]
rule

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|label
|string
|True
a|

|retention
|string
|True
a|

|===


[#cloud-storage-pool]
[.api-collapsible-fifth-title]
cloud-storage-pool

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|provider
|string
|True
a|Cloud provider where the cloud storage pool is hosted


|provider-account-id
|string
|True
a|Cloud provider account ID where the cloud storage pool is hosted


|region
|string
|True
a|Cloud provider region where the cloud storage pool is hosted


|archive-storage-class
|string
|False
a|Required for AWS to specify which storage class to use for archiving


|resource-group
|string
|False
a|Required when the provider is Azure


|===


[#sgws-archival]
[.api-collapsible-fifth-title]
sgws-archival

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|cloud-storage-pool
|link:#cloud-storage-pool[cloud-storage-pool]
|True
a|

|===


[#backup-policy]
[.api-collapsible-fifth-title]
backup-policy

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Required input


|rule
|array[link:#rule[rule]]
|False
a|

|archive-after-days
|string
|False
a|

|object-lock
|string
|False
a|

|sgws-archival
|link:#sgws-archival[sgws-archival]
|False
a|

|===


[#replication]
[.api-collapsible-fifth-title]
replication

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|working-environment-id
|string
|True
a|

|working-environment-name
|string
|True
a|

|svm
|string
|True
a|

|policy-name
|string
|True
a|

|prefix
|string
|False
a|

|suffix
|string
|False
a|

|destination-aggregates
|array[string]
|True
a|

|===


[#is-enabled]
[.api-collapsible-fifth-title]
is-enabled

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|local-snapshot
|boolean
|True
a|

|replication
|boolean
|True
a|

|cloud-backup
|boolean
|True
a|

|===


[#private-endpoint]
[.api-collapsible-fifth-title]
private-endpoint

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|id
|string
|True
a|Optional input field for a private endpoint


|===


[#aws]
[.api-collapsible-fifth-title]
aws

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|account-id
|string
|True
a|Required when the provider is AWS


|kms-key-id
|string
|False
a|Optional input field for customer managed key use case


|private-endpoint
|link:#private-endpoint[private-endpoint]
|False
a|

|archive-storage-class
|string
|False
a|Required for AWS to specify which storage class to use for archiving


|===


[#private-endpoint]
[.api-collapsible-fifth-title]
private-endpoint

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|subnet
|string
|False
a|Required input field for on-premises private link configuration


|skip-creation
|boolean
|False
a|Optional input field to skip private endpoint creation


|===


[#key-vault]
[.api-collapsible-fifth-title]
key-vault

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|key-vault-id
|string
|True
a|

|key-name
|string
|True
a|

|===


[#azure]
[.api-collapsible-fifth-title]
azure

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|resource-group
|string
|True
a|Required when the provider is Azure


|storage-account
|string
|False
a|Required when the provider is Azure


|subscription
|string
|True
a|Required when the provider is Azure


|private-endpoint
|link:#private-endpoint[private-endpoint]
|False
a|

|key-vault
|link:#key-vault[key-vault]
|False
a|

|===


[#kms]
[.api-collapsible-fifth-title]
kms

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|key-ring-id
|string
|True
a|

|crypto-key-id
|string
|True
a|

|===


[#gcp]
[.api-collapsible-fifth-title]
gcp

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|project-id
|string
|False
a|Required when the provider is Google Cloud


|access-key
|string
|False
a|Required input field for on-premises use case


|secret-password
|string
|False
a|Required input field for on-premises use case


|credentials-id
|string
|False
a|Google Cloud credentials ID. Required when the provider is Google Cloud


|kms
|link:#kms[kms]
|False
a|

|===


[#sgws]
[.api-collapsible-fifth-title]
sgws

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|storage-grid-id
|string
|False
a|StorageGRID ID. Required input field for StorageGRID provider


|storage-server-name
|string
|False
a|StorageGRID server name. Required input field for a StorageGRID provider


|storage-server
|string
|False
a|StorageGRID server URL with port. Required input field for a StorageGRID provider


|access-key
|string
|False
a|Required input field for on-premises use case.


|secret-password
|string
|False
a|Required input field for on-premises use case.


|credential-id
|string
|False
a|StorageGRID credential ID for fetching credential from credential service


|===


[#ontap-s3]
[.api-collapsible-fifth-title]
ontap-s3

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|storage-server
|string
|False
a|ONTAP S3 server URL. Required input field for ONTAP_S3 provider.


|access-key
|string
|False
a|Optional input field for on-premises use case.


|secret-password
|string
|False
a|Required input field for on-premises use case.


|credential-id
|string
|False
a|ONTAP S3 credential ID for fetching credentials from the credential service.


|===


[#s3-compatible]
[.api-collapsible-fifth-title]
s3-compatible

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|storage-server
|string
|True
a|S3 storage server.


|access-key
|string
|True
a|Required input field for on-premises use case.


|secret-password
|string
|True
a|Required input field for on-premises use case


|===


[#object-storage-details]
[.api-collapsible-fifth-title]
object-storage-details

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|object-storage-name
|string
|False
a|Object storage name to be used for protection. If not provided, the name is auto-generated.


|provider
|string
|True
a|Required input field for on-premises use case

* enum: ["AWS", "AZURE", "GCP", "SGWS", "ONTAP_S3", "S3_COMPATIBLE"]


|region
|string
|False
a|Required input field


|ip-space
|string
|False
a|Required input field for on-premises use case


|aws
|link:#aws[aws]
|False
a|

|azure
|link:#azure[azure]
|False
a|

|gcp
|link:#gcp[gcp]
|False
a|

|sgws
|link:#sgws[sgws]
|False
a|

|ontap-s3
|link:#ontap-s3[ontap-s3]
|False
a|

|s3-compatible
|link:#s3-compatible[s3-compatible]
|False
a|

|===


[#volumes]
[.api-collapsible-fifth-title]
volumes

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|volume-id
|string
|True
a|

|volume-name
|string
|True
a|

|source-snapshot
|string
|False
a|Optional existing local snapshot used as the backup source


|architecture
|string
|False
a|Type of storage architecture. Fan-out or cascading.


|workload
|string
|False
a|

|mode
|string
|True
a|

|type
|string
|False
a|

|backup-policy
|link:#backup-policy[backup-policy]
|False
a|

|snapshot-policy
|string
|False
a|Snapshot policy name


|replication
|link:#replication[replication]
|False
a|

|is-enabled
|link:#is-enabled[is-enabled]
|True
a|

|object-storage-details
|array[link:#object-storage-details[object-storage-details]]
|False
a|

|===


//end collapsible .Definitions block
====
