---
sidebar: sidebar
api: true
explorer: false
permalink: 'cbs/post-account-providers-cloudmanager_cbs-api-v2-gcp-credentials.html'
summary: 'Register Google Cloud credentials'
---

= Register Google Cloud credentials

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/account/{accountId}/providers/cloudmanager_cbs/api/v2/gcp/credentials`#



Registers Google Cloud credentials for a Google Cloud project in the NetApp Console SaaS application.

**Token usage:** NetApp Console user token.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|accountId
|string
|path
|True
a|Account ID


|authorization
|string
|header
|True
a|User token


|X-Agent-Id
|string
|header
|True
a|Request identifier

|===

== Request Body

                

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|credentials-id
|string
|True
a|Credentials ID. Must only contain lower case alphabetic characters, numbers and hyphen(-). Must start and end with an alphabetic character or number.


|access-key
|string
|True
a|Google Cloud access-key.


|secret-password
|string
|True
a|Google Cloud secret-password.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "credentials-id": "string",
  "access-key": "string",
  "secret-password": "string"
}
====

== Response

```
Status: 200, Default response
```



== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#body]
[.api-collapsible-fifth-title]
body

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|credentials-id
|string
|True
a|Credentials ID. Must only contain lower case alphabetic characters, numbers and hyphen(-). Must start and end with an alphabetic character or number.


|access-key
|string
|True
a|Google Cloud access-key.


|secret-password
|string
|True
a|Google Cloud secret-password.


|===


//end collapsible .Definitions block
====
