---
sidebar: sidebar
api: true
explorer: false
permalink: 'cbs/put-account-providers-cloudmanager_cbs-api-v2-backup-working-environment-.html'
summary: 'Modify the Backup and Recovery service backup configuration'
---

= Modify the Backup and Recovery service backup configuration

[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/account/{accountId}/providers/cloudmanager_cbs/api/v2/backup/working-environment/{workingEnvironmentId}`#



Modifies the NetApp Backup and Recovery service backup configuration for a particular system synchronously (V2 version). You can modify the state, backup policy, archive storage class, cloud storage pool, AWS/Azure/Google Cloud/StorageGRID access and secret key, IPspace, maximum transfer rate, and enable automatic backup.

**Token usage:** NetApp Console user token.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|accountId
|string
|path
|True
a|Account ID


|workingEnvironmentId
|string
|path
|True
a|System ID of the source Cloud Volumes ONTAP instance


|authorization
|string
|header
|True
a|User token


|X-Agent-Id
|string
|header
|True
a|Request identifier

|===

== Request Body

                

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|state
|string
|False
a|Updates the SnapMirror relationship state in the system to the specified state


|backup-policy
|link:#backup-policy[backup-policy]
|False
a|Uses an existing policy or creates a new policy if not found in the list of ONTAP policies and modifies the backed up system relationships to use the existing one.


|archive-storage-class
|string
|False
a|Required for AWS if modifying the storage class or enabling archive for the first time.


|auto-backup-enabled
|boolean
|False
a|Automatically backs up all volumes in the systems


|max-transfer-rate
|number
|False
a|Modifies node-level throttling of an ONTAP cluster. Value to be specified in kilo bytes per second(kbps). A value of 0 implies unlimited throttling


|delete-yearly-snapshots
|boolean
|False
a|Disables the deletion of local yearly snapshots after being transferred to object store


|export-existing-snapshots
|boolean
|False
a|Exports pre-existing snapshots to object storage


|ip-space
|string
|False
a|IP space for the backed up system


|toggle-rsw-scan
|boolean
|False
a|Toggles RSW scheduled scan on or off


|rsw-scan-interval
|string
|False
a|RSW scheduled scans interval


|aws
|link:#aws[aws]
|False
a|Accesses key and secret password for the system


|gcp
|link:#gcp[gcp]
|False
a|Accesses key and secret password for the system


|sgws
|link:#sgws[sgws]
|False
a|Accesses key and secret password for the system


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "state": "string",
  "backup-policy": {
    "name": "string",
    "rule": [
      {
        "label": "string",
        "retention": "string"
      }
    ],
    "archive-after-days": "string",
    "object-lock": "string",
    "sgws-archival": {
      "cloud-storage-pool": {
        "provider": "string",
        "provider-account-id": "string",
        "region": "string",
        "access-key": "string",
        "secret-password": "string",
        "archive-storage-class": "string",
        "resource-group": "string"
      }
    }
  },
  "archive-storage-class": "string",
  "ip-space": "string",
  "rsw-scan-interval": "string",
  "aws": {
    "access-key": "string",
    "secret-password": "string"
  },
  "gcp": {
    "access-key": "string",
    "secret-password": "string"
  },
  "sgws": {
    "access-key": "string",
    "secret-password": "string",
    "storage-grid-id": "string"
  }
}
====

== Response

```
Status: 202, Default response
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|job-id
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job-id": "string"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#rule]
[.api-collapsible-fifth-title]
rule

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|label
|string
|False
a|

|retention
|string
|False
a|

|===


[#cloud-storage-pool]
[.api-collapsible-fifth-title]
cloud-storage-pool

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|provider
|string
|True
a|Cloud provider where the cloud storage pool is hosted


|provider-account-id
|string
|True
a|Cloud provider account ID where the cloud storage pool is hosted


|region
|string
|True
a|Cloud provider region where the cloud storage pool is hosted


|access-key
|string
|False
a|Required input field if the provider is AWS


|secret-password
|string
|False
a|Required input field if the provider is AWS


|archive-storage-class
|string
|False
a|Required for AWS to specify which storage class to use for archiving


|resource-group
|string
|False
a|Required when the provider is Azure


|===


[#sgws-archival]
[.api-collapsible-fifth-title]
sgws-archival

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|cloud-storage-pool
|link:#cloud-storage-pool[cloud-storage-pool]
|False
a|

|===


[#backup-policy]
[.api-collapsible-fifth-title]
backup-policy

Uses an existing policy or creates a new policy if not found in the list of ONTAP policies and modifies the backed up system relationships to use the existing one.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|False
a|Policy name of the existing policy or any custom name with which a new policy needs to be created. If not specified, a policy with the NetApp Backup and Recovery service default naming convention is created.


|rule
|array[link:#rule[rule]]
|False
a|Specifies the rules for a new policy


|archive-after-days
|string
|False
a|

|object-lock
|string
|False
a|

|sgws-archival
|link:#sgws-archival[sgws-archival]
|False
a|

|===


[#aws]
[.api-collapsible-fifth-title]
aws

Accesses key and secret password for the system


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|access-key
|string
|False
a|

|secret-password
|string
|False
a|

|===


[#gcp]
[.api-collapsible-fifth-title]
gcp

Accesses key and secret password for the system


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|access-key
|string
|False
a|

|secret-password
|string
|False
a|

|===


[#sgws]
[.api-collapsible-fifth-title]
sgws

Accesses key and secret password for the system


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|access-key
|string
|False
a|

|secret-password
|string
|False
a|

|storage-grid-id
|string
|False
a|StorageGRID ID. Required input field for StorageGRID provider


|===


[#body]
[.api-collapsible-fifth-title]
body

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|state
|string
|False
a|Updates the SnapMirror relationship state in the system to the specified state


|backup-policy
|link:#backup-policy[backup-policy]
|False
a|Uses an existing policy or creates a new policy if not found in the list of ONTAP policies and modifies the backed up system relationships to use the existing one.


|archive-storage-class
|string
|False
a|Required for AWS if modifying the storage class or enabling archive for the first time.


|auto-backup-enabled
|boolean
|False
a|Automatically backs up all volumes in the systems


|max-transfer-rate
|number
|False
a|Modifies node-level throttling of an ONTAP cluster. Value to be specified in kilo bytes per second(kbps). A value of 0 implies unlimited throttling


|delete-yearly-snapshots
|boolean
|False
a|Disables the deletion of local yearly snapshots after being transferred to object store


|export-existing-snapshots
|boolean
|False
a|Exports pre-existing snapshots to object storage


|ip-space
|string
|False
a|IP space for the backed up system


|toggle-rsw-scan
|boolean
|False
a|Toggles RSW scheduled scan on or off


|rsw-scan-interval
|string
|False
a|RSW scheduled scans interval


|aws
|link:#aws[aws]
|False
a|Accesses key and secret password for the system


|gcp
|link:#gcp[gcp]
|False
a|Accesses key and secret password for the system


|sgws
|link:#sgws[sgws]
|False
a|Accesses key and secret password for the system


|===


//end collapsible .Definitions block
====
