---
sidebar: sidebar
api: true
explorer: false
permalink: 'tenancyv4/hierarchy_overview.html'
summary: 'Hierarchy endpoints in the identity and access management REST API for the NetApp Console'
---

= Hierarchy endpoints in the identity and access management REST API for the NetApp Console



The hierarchy endpoints enable you to accurately represent your organization's complete resource hierarchy using folders and projects.

A Hierarchy is composed of multiple elements:

* The organization is the top of the NetApp Console IAM hierarchy. Optionally, you can also have a child organization under a parent organization. An organization represents a purchaser of goods or services from NetApp.
* Folders are children of the organization or of another folder. Folders are optional in NetApp Console IAM and can represent a city, department, region, deployment environment, and so on.
* Projects are children of the organization or of a folder. Projects represent a working space in NetApp Console that organization members can access to manage resources.
* Resources are associated with one or more folders or projects.


