---
sidebar: sidebar
api: true
explorer: false
permalink: 'tenancyv4/partnership_overview.html'
summary: 'Partnership endpoints in the identity and access management REST API for the NetApp Console'
---

= Partnership endpoints in the identity and access management REST API for the NetApp Console



The partnership endpoints enable collaboration between two organizations in the NetApp Console.

A partnership represents an organization sharing resources (the source organization) with users of a different organization (the destination organization).  Partnership allows the source organization to grant permissions to users from the destination organization, enabling them to manage one or more organization's resources. Grants define the access (set of permissions) that a user from the destination organization has on a resource from the source organization.

A partnership has multiple grants. A grant is defined by:

* A list of users from the destination organization
* A list of resources from the source organization
* A role applicable between these two groups which is referenced in the partnershipType.

The partnership type defines the possible roles that can be applied between users and resources. The current supported partnership types are Self-Service.


