---
sidebar: sidebar
api: true
explorer: false
permalink: 'copysync/get-api-accounts-info.html'
summary: 'Retrieve the account information'
---

= Retrieve the account information

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/api/accounts/info`#



Retrieves the account information.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|noCreate
|boolean
|query
|False
a|Don't create the requested account if it doesn't already exist


|x-account-id
|string
|header
|True
a|NetApp tenancy account ID


|===

== Response

```
Status: 200, Default Response
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|accountId
|string
|True
a|The logged in account's tenancy ID


|name
|string
|True
a|The logged in account's name as retrieved from the OAuth provider


|noCharge
|boolean
|True
a|Indicates whether all the relationships are Azure NetApp Files


|daysLeftForTrial
|number
|True
a|Days left for a free trial or (-1) if the trial has already expired


|subscriptionType
|string
|True
a|Subscription type


|subscriptionStatus
|string
|True
a|The account's AWS marketplace subscription status


|subscriptionProvider
|string
|True
a|SaaS subscription type


|===


