---
sidebar: sidebar
api: true
explorer: false
permalink: 'copysync/get-api-accounts-license-settings.html'
summary: 'Retrieve license settings'
---

= Retrieve license settings
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/api/accounts/license-settings`#



Retrieves the license settings.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|x-account-id
|string
|header
|True
a|NetApp tenancy account ID


|===

== Response

```
Status: 200, Default Response
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|freeTrial
|boolean
|True
a|If it is on free trial period


|existingRelationships
|number
|True
a|The number of the existing relationships


|reservedRelationships
|number
|True
a|The number of the BYOL relationships used


|totalReservedRelationships
|number
|True
a|The total number of the BYOL relationships available


|chargedRelationships
|number
|True
a|The number of the charged relationships


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "freeTrial": false,
  "existingRelationships": 0,
  "reservedRelationships": 0,
  "totalReservedRelationships": 0,
  "chargedRelationships": 0
}
====

