---
sidebar: sidebar
api: true
explorer: false
permalink: 'copysync/post-api-data-brokers.html'
summary: 'Create a new installer for the NetApp data broker instance'
---

= Create a new installer for the NetApp data broker instance

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/api/data-brokers`#



Creates a new installer for the NetApp data broker instance.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|x-account-id
|string
|header
|True
a|NetApp tenancy account ID


|===

== Request Body

                   

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|

|groupId
|string
|False
a|

|port
|number
|False
a|

|certificate
|string
|False
a|For Listener data broker - if the user wants his own certificate


|privateKey
|string
|False
a|For Listener data broker - if the user wants his own certificate


|serverName
|string
|False
a|For Listener data broker - if the user wants his own certificate


|type
|string
|True
a|

|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "name": "string",
  "groupId": "string",
  "certificate": "string",
  "privateKey": "string",
  "serverName": "string",
  "type": "string"
}
====

== Response

```
Status: 200, Default Response
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|id
|string
|True
a|Data Broker ID


|groupId
|string
|True
a|Data Broker group ID


|type
|string
|True
a|Data Broker type


|latestVersion
|string
|False
a|Data Broker latest version available


|fileLink
|string
|True
a|Data Broker installer or template link


|name
|string
|True
a|Data Broker name


|template
|["string", "object"]
|False
a|Data Broker template - relevant for GCP/AZURE/AWS


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "id": "string",
  "groupId": "string",
  "type": "string",
  "latestVersion": "string",
  "fileLink": "string",
  "name": "string"
}
====

