---
sidebar: sidebar
api: true
explorer: false
permalink: 'copysync/put-api-relationships-v2-.html'
summary: 'Update the settings for a relationship'
---

= Update the settings for a relationship

[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/api/relationships-v2/{id}`#



Updates the settings for a relationship.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|id
|string
|path
|True
a|Relationship ID


|x-account-id
|string
|header
|True
a|NetApp tenancy account ID


|===

== Request Body

                   

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|gracePeriod
|number
|False
a|Grace period time ( seconds )


|deleteOnSource
|boolean
|False
a|Enable delete on source


|deleteOnTarget
|boolean
|False
a|Enable delete on target


|objectTagging
|boolean
|False
a|Use S3 tagging to store object metadata


|retries
|integer
|False
a|Number of retries


|copyAcl
|boolean
|False
a|Enable ACL copy


|copyData
|boolean
|False
a|Copy data only


|continuousSync
|boolean
|False
a|Listen to object notifications


|fileTypes
|link:#fileTypes[fileTypes]
|False
a|The file types that is included in the relationship


|compareBy
|link:#compareBy[compareBy]
|False
a|The file attributes that should be compared


|copyProperties
|link:#copyProperties[copyProperties]
|False
a|The object properties that should be copied


|files
|link:#files[files]
|False
a|Settings related to files.


|directories
|link:#directories[directories]
|False
a|Settings related to directories.


|schedule
|link:#schedule[schedule]
|False
a|Sync schedule settings.


|notifications
|link:#notifications[notifications]
|False
a|Notifications settings.


|scheduleAbort
|link:#scheduleAbort[scheduleAbort]
|False
a|Schedule abort settings.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "files": {
    "excludeExtensions": [
      "string"
    ],
    "excludeByRegex": [
      "string"
    ],
    "minDate": "string",
    "minCreationDate": "string"
  },
  "directories": {
    "excludeNames": [
      "string"
    ],
    "excludeByRegex": [
      "string"
    ]
  },
  "schedule": {
    "nextTime": "string"
  }
}
====

== Response

```
Status: 200, Default Response
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|gracePeriod
|number
|True
a|Grace period time ( seconds )


|deleteOnSource
|boolean
|True
a|Enable delete on source


|deleteOnTarget
|boolean
|True
a|Enable delete on target


|objectTagging
|boolean
|True
a|Use S3 tagging to store object metadata


|retries
|integer
|True
a|Number of retries


|copyAcl
|boolean
|False
a|Enable ACL copy


|copyData
|boolean
|True
a|Copy data only


|continuousSync
|boolean
|False
a|Listen to object notifications


|fileTypes
|link:#fileTypes[fileTypes]
|True
a|The file types that is included in the relationship


|compareBy
|link:#compareBy[compareBy]
|True
a|The file attributes that should be compared


|copyProperties
|link:#copyProperties[copyProperties]
|False
a|The object properties that should be copied


|files
|link:#files[files]
|True
a|Settings related to files.


|directories
|link:#directories[directories]
|True
a|Settings related to directories.


|schedule
|link:#schedule[schedule]
|True
a|Sync schedule settings.


|notifications
|link:#notifications[notifications]
|False
a|Notifications settings.


|scheduleAbort
|link:#scheduleAbort[scheduleAbort]
|True
a|Schedule abort settings.


|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#fileTypes]
[.api-collapsible-fifth-title]
fileTypes

The file types that is included in the relationship


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|files
|boolean
|False
a|Include files


|directories
|boolean
|False
a|Include directories


|symlinks
|boolean
|False
a|Include symbolic links


|hardlinks
|boolean
|False
a|include hard links


|===


[#compareBy]
[.api-collapsible-fifth-title]
compareBy

The file attributes that should be compared


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|uid
|boolean
|False
a|uid ( relevant when source or target is file system )


|gid
|boolean
|False
a|gid ( relevant when source or target is file system )


|mtime
|boolean
|False
a|mtime


|mode
|boolean
|False
a|mode


|===


[#copyProperties]
[.api-collapsible-fifth-title]
copyProperties

The object properties that should be copied


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|metadata
|boolean
|False
a|copy metadata ( cloud to cloud )


|tags
|boolean
|False
a|copy tags ( cloud to cloud only S3 compatible )


|===


[#files]
[.api-collapsible-fifth-title]
files

Settings related to files.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|excludeExtensions
|array[string]
|False
a|Excluded extensions array (For example - [".log", ".tar.gz"])


|excludeByRegex
|array[string]
|False
a|Excluded files by regex (For example - ".txt." will exclude the files file.doc.txt.gz)


|minSize
|integer
|False
a|Minimum file size (in bytes). Only files of equal or larger size will be transferred by the relationship


|maxSize
|integer
|False
a|Maximum file size (in bytes). Only files of equal or smaller size will be transferred by the relationship


|minDate
|string
|False
a|Data broker will sync files that were last modified after this date. The date must be an ISO 8601 valid date. For example - '2012-02-21'


|maxDate
|["null", "string"]
|False
a|Data broker will sync files that were last modified before this date. Insert 'null' to sync all future files. The date must be an ISO 8601 valid date


|minCreationDate
|string
|False
a|Data broker will sync files that were created after this date. The date must be an ISO 8601 valid date. For example - '2012-02-21'


|maxCreationDate
|["null", "string"]
|False
a|Data broker will sync files that were created before this date. Insert 'null' to sync all future files. The date must be an ISO 8601 valid date


|===


[#directories]
[.api-collapsible-fifth-title]
directories

Settings related to directories.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|excludeNames
|array[string]
|False
a|Excluded directories names array (For example - ["dir1"])


|excludeByRegex
|array[string]
|False
a|Excluded directories names by regex (For example - "._tmp._." will exclude the directories with names that include tmp )


|===


[#schedule]
[.api-collapsible-fifth-title]
schedule

Sync schedule settings.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|syncInDays
|integer
|False
a|Days interval for sync scheduler


|syncInHours
|integer
|False
a|

|syncInMinutes
|integer
|False
a|

|isEnabled
|boolean
|False
a|Activate automatic scheduler


|nextTime
|string
|False
a|The first time the relationship should run


|syncWhenCreated
|boolean
|False
a|Start the sync upon creation


|===


[#cm]
[.api-collapsible-fifth-title]
cm

NetApp Console notifications


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|done
|boolean
|False
a|Should send notification about DONE status


|failed
|boolean
|False
a|Should send notification about FAILED status


|aborted
|boolean
|False
a|Should send notification about ABORTED status


|running_continuously
|boolean
|False
a|Should send notification about RUNNING_CONTINUOUSLY status


|===


[#notifications]
[.api-collapsible-fifth-title]
notifications

Notifications settings.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|cm
|link:#cm[cm]
|False
a|NetApp Console notifications


|===


[#scheduleAbort]
[.api-collapsible-fifth-title]
scheduleAbort

Schedule abort settings.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|abortInDays
|integer
|False
a|Days interval for abort scheduler


|abortInHours
|integer
|False
a|Hours interval for abort scheduler


|abortInMinutes
|integer
|False
a|Minutes interval for abort scheduler


|isEnabled
|boolean
|False
a|Activate automatic scheduler abort


|===


//end collapsible .Definitions block
====
