---
sidebar: sidebar
api: true
explorer: false
permalink: 'federation/get-organizations-domains-.html'
summary: 'Retrieve a domain'
---

= Retrieve a domain

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/organizations/{organization_id}/domains/{domain_id}`#



Retrieves the specified domain.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|organization_id
|string
|path
|True
a|Identifier for an organization.


|domain_id
|string
|path
|True
a|ID of the domain.

* example: 4336388b-2992-43af-81de-ba9284b7dc36


|include
|string
|query
|False
a|Specifies which fields should be returned when listing a collection.

URL examples: "include=id", "include=id,name"

OpenAPI examples: "id"


|===

== Response

```
Status: 200, Returns the stored domain in the JSON response body.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|code
|string
|False
a|The unique verification code for this domain.


|federations
|array[link:#federations[federations]]
|False
a|The list of federations that use this domain.


|id
|string
|False
a|Globally unique identifier of the resource conforming to the UUIDv4 schema.


|metadata
|link:#type_bxp_metadata[type_bxp_metadata]
|False
a|Metadata associated with the resource.


|name
|string
|False
a|The domain name.


|organizationId
|string
|False
a|Identifier for an organization.


|resourceId
|string
|False
a|Identifier for the resource.


|state
|string
|False
a|The state of the domain.
Defined values are:

* "UNVERIFIED" - Ownership of the domain has not been verified.
* "VERIFIED" - Ownership of the domain has been verified using a DNS TXT record with the verification code.


|type
|string
|False
a|Media type of the resource.


|verificationTimestamp
|string
|False
a|The date that the domain was verified.


|version
|string
|False
a|Version of the resource.


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "code": "Console133ad2ea-99de-4ada-9be4-876d4d53923e",
  "federations": [
    {
      "id": "4336388b-2992-43af-81de-ba9284b7dc36",
      "name": "Example Co. AD FS"
    },
    {
      "id": "645eae30-ea32-4542-af58-1d9012fed81a",
      "name": "Example Co. SAML"
    }
  ],
  "id": "4336388b-2992-43af-81de-ba9284b7dc36",
  "metadata": {
    "createdBy": "666a3f38-d4fa-5b62-a391-a69029758d32",
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "labels": [
      {
        "name": "string",
        "value": "string"
      }
    ],
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modifiedBy": "666a3f38-d4fa-5b62-a391-a69029758d32"
  },
  "name": "example.com",
  "organizationId": "9b0ee210-70a0-4158-b025-0decde66e4de",
  "resourceId": "862b6f03-58ac-479b-9ca5-5cb4429d8996",
  "state": "VERIFIED",
  "type": "application/vnd.netapp.bxp.domain",
  "verificationTimestamp": "2024-11-18T20:58:16.305662Z",
  "version": "1.0"
}
====

== Error

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The supplied query parameters are invalid.",
  "status": "400",
  "title": "Invalid query parameters",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The request is missing the required bearer token.",
  "status": "401",
  "title": "Missing bearer token",
  "type": "https://bluexp.netapp.io/problems/1"
}
====

== Error

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The requested operation isn't permitted.",
  "status": "403",
  "title": "Operation not permitted",
  "type": "https://bluexp.netapp.io/problems/11"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|correlationId
|string
|False
a|Internal UUID representing the request or trace ID related.


|detail
|string
|False
a|Details about the problem.


|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid parameters.


|status
|string
|True
a|HTTP error code related to the problem.


|title
|string
|True
a|Title description of the problem.


|type
|string
|True
a|Content-type of the object.


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404",
  "title": "Collection not found",
  "type": "https://bluexp.netapp.io/problems/2"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#federations]
[.api-collapsible-fifth-title]
federations

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|id
|string
|False
a|Globally unique identifier of the resource conforming to the UUIDv4 schema.


|name
|string
|False
a|The name of the federation.


|===


[#type_bxp_label]
[.api-collapsible-fifth-title]
type_bxp_label

Name/value pair.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the label.


|value
|string
|True
a|Value of the label.


|===


[#type_bxp_metadata]
[.api-collapsible-fifth-title]
type_bxp_metadata

Metadata associated with the resource.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|createdBy
|string
|False
a|UUID of the user who created the resource.


|creationTimestamp
|string
|False
a|Resource creation date.


|labels
|array[link:#type_bxp_label[type_bxp_label]]
|False
a|Array of name/value pairs representing additional information for the resource.


|modificationTimestamp
|string
|False
a|Resource modification date.


|modifiedBy
|string
|False
a|UUID of the user who modified the resource.


|===


[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid parameter.


|reason
|string
|True
a|Reason why the parameter is invalid.


|===


//end collapsible .Definitions block
====
