---
sidebar: sidebar
permalink: cm/prepare.html
keywords: bluexp, rest, api, credentials, cloud, volumes, ONTAP, API, netapp, console
summary: 'There are several things you should do to prepare to use the NetApp Console REST API and associated workflows.'
---

= Prepare to use the NetApp Console ONTAP management REST API 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You need to prepare before using the REST APIs provided with ONTAP management. 

== Step 1: Obtain NetApp Console credentials
You need a NetApp account to acquire the access token required to issue the REST API calls. Refer to https://docs.netapp.com/us-en/console-setup-admin/task-sign-up-saas.html[Sign up or log in to NetApp Console^] for more information.

== Step 2: Review REST concepts and implementation
Review the link:../platform/concepts.html[REST implementation details] for information about REST concepts and the details of how a REST API is designed.

== Step 3: Review the Cloud Volumes ONTAP and ONTAP on-premises concepts
If you plan to perform Cloud Volumes ONTAP and on-premises ONTAP administration tasks, you need to be familiar with the related ONTAP concepts, terminology, and procedures. Learn about link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-overview-cvo.html[Cloud Volumes ONTAP^] and https://docs.netapp.com/us-en/storage-management-ontap-onprem/concept-onprem-ontap.html[on-premises ONTAP^] concepts.


== Step 4: Decide on the cloud provider and obtain credentials for Cloud Volumes ONTAP
Cloud Volumes ONTAP can be deployed in AWS, Microsoft Azure, and Google Cloud platform. You need to decide which of these providers you'll use and have the appropriate credentials.

== Step 5: Decide on the licensing model for Cloud Volumes ONTAP
You can create and manage Cloud Volumes ONTAP instances using a subscription PAYGO ("pay as you go") model or apply your own licenses with BYOL ("bring your own license"). You need to decide which licensing model to use and adjust the workflows as needed.

== Step 6: Prepare to use the workflow processes
Review link:workflow_processes.html[Workflow processes] for more information about the organization and content of the Cloud Volumes ONTAP and on-premises ONTAP workflows. 
[NOTE]
This documentation does not describe or use the legacy UI (not the SaaS UI).

== Step 7: Locate the identifiers
You need the identifier values for several of the workflows. Refer to link:../platform/get_identifiers.html[Get required identifiers] for more information.

== Step 8: Review additional considerations
Review the available resources described in link:../platform/additional_considerations.html[Additional considerations].
