---
sidebar: sidebar
permalink: cm/wf_aws_ontap_get_cifs.html
keywords: cloud, manager, rest, api
summary: "You can use this workflow to retrieve the Common Internet File System (CIFS) server configurations for an existing Cloud Volumes ONTAP system."
---

= Get CIFS server configurations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can use this workflow to retrieve the Common Internet File System (CIFS) server configurations for an existing Cloud Volumes ONTAP system.

Choose the correct workflow depending on the type of the Cloud Volumes ONTAP deployment:

* <<Get CIFS server configuration for single node, Single Node>>
* <<Get CIFS server configuration for high availability pair, HA pair>>

== Get CIFS server configuration for single node
You can use this workflow to retrieve a CIFS server configuration for a single node system.

=== Step 1. Select the system

Perform the workflow link:wf_aws_cloud_get_wes.html#get-systems-for-a-single-node[Get systems] and choose the `publicId` value of the system for the `workingEnvironmentId` path parameter.

=== Step 2. Get the CIFS configurations

You can issue the REST API call to get the CIFS configurations.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/occm/api/vsa/working-environments/{workingEnvironmentId}/cifs
|===

.Curl example
[source,curl]
curl --request GET \
--location "https://api.bluexp.netapp.com/occm/api/vsa/working-environments/<WORKING_ENV_ID>/cifs" \
--header "Content-Type: application/json" \
--header "x-agent-id: <AGENT_ID>" \
--header "Authorization: Bearer <ACCESS_TOKEN>"

.Additional input parameters

The JSON input example includes the minimum list of parameters.


[cols="25,25, 25, 45"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|<SVM_NAME> |Query |No |Identifies the SVM
|`workingEnvironmentId` <WORKING_ENV_ID> |Path |Yes |Identifies the system ID
|===

.Output

The JSON output example includes the CIFS configurations for an existing Cloud Volumes ONTAP system.

.JSON output example
----
[
    {
        "dnsDomain": "zivh.netapp.com",
        "activeDirectoryDomain": "zivh.netapp.com",
        "ipAddresses": [
            "172.31.5.241"
        ],
        "netBIOS": "zivaws02we01",
        "organizationalUnit": "CN=Computers",
        "authenticationType": "domain"
    }
]
----

== Get CIFS server configuration for high availability pair
You can use this workflow to retrieve a CIFS server configuration for an HA system.

=== Step 1. Select the system

Perform the workflow link:wf_aws_cloud_get_wes.html#get-systems-for-a-high-availability-pair[Get systems] and choose the `publicId` value of the system for the `workingEnvironmentId` path parameter.

=== Step 2. Get the CIFS configurations

You can issue the REST API call to get the CIFS configurations.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/occm/api/aws/ha/working-environments/{workingEnvironmentId}/cifs
|===

.Curl example
[source,curl]
curl --request GET \
--location "https://api.bluexp.netapp.com/occm/api/aws/ha/working-environments/<WORKING_ENV_ID>/cifs" \
--header "Content-Type: application/json" \
--header "x-agent-id: <AGENT_ID>" \
--header "Authorization: Bearer <ACCESS_TOKEN>"

.Additional input parameters

The JSON input example includes the minimum list of parameters.


[cols="25,25, 25, 45"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|<SVM_NAME> |Query |No |Identifies the SVM
|`workingEnvironmentId` <WORKING_ENV_ID> |Path |Yes |Identifies the system ID
|===

.Output

The JSON output example includes the CIFS configurations for an existing Cloud Volumes ONTAP system.

.JSON output example
----
[
    {
        "dnsDomain": "zivh.netapp.com",
        "activeDirectoryDomain": "zivh.netapp.com",
        "ipAddresses": [
            "172.31.5.241"
        ],
        "netBIOS": "zivaws02we01",
        "organizationalUnit": "CN=Computers",
        "authenticationType": "domain"
    }
]
----
