---
sidebar: sidebar
permalink: cm/wf_aws_cloud_get_wes.html
keywords: cloud, manager, rest, api, list, working, environment, occm
summary: "You can retrieve the Cloud Volumes ONTAP systems that are visible to the user currently signed in."
---

= Get systems
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can retrieve the public identifier, system identifier, and the storage virtual machine name for Cloud Volumes ONTAP systems (visible to currently logged in user) which will be used in other workflows.

Choose the workflow to use based on the type of the Cloud Volumes ONTAP deployment:

* <<Get systems for a single node, Single Node>>
* <<Get systems for a high availability pair, HA pair>>


== Get systems for a single node

You can use this workflow to retrieve the system details for a single node system.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|occm/api/vsa/working-environments
|===

.Curl example
[source,curl]
curl --request GET \
--location "https://api.bluexp.netapp.com/occm/api/vsa/working-environments" \
--header "x-agent-id: <AGENT_ID>" \ 
--header "Authorization: Bearer <ACCESS_TOKEN>" \
--header "Content-Type: application/json"

.Additional input parameters

In addition to the parameters common with all REST API calls, the following parameters are also used in the curl example in this step.

[cols="25,25, 25, 45"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
| `fields` |Query |No |Identifies the number of fields you will retrieve
| `tenantId` |Query |No |Identifies the tenant ID.
|===



.JSON output example
The JSON output example includes an array of VSA systems and their details.

.Example output
[%collapsible]
====
----
[
    {
        "publicId": "VsaWorkingEnvironment-79VKenHW",
        "name": "ziv01we02",
        "tenantId": "tenantIDshownhere",
        "svmName": "svm_ziv01we02",
        "creatorUserEmail": "user_email",
        "status": null,
        "awsProperties": null,
        "reservedSize": null,
        "encryptionProperties": null,
        "clusterProperties": null,
        "ontapClusterProperties": null,
        "actionsRequired": null,
        "interClusterLifs": null,
        "cronJobSchedules": null,
        "snapshotPolicies": null,
        "svms": null,
        "activeActions": null,
        "replicationProperties": null,
        "schedules": null,
        "cloudProviderName": "Amazon",
        "isHA": false,
        "workingEnvironmentType": "VSA",
        "supportRegistrationProperties": null,
        "supportRegistrationInformation": [],
        "haProperties": null,
        "capacityFeatures": null,
        "cloudSyncProperties": null,
        "supportedFeatures": null,
        "k8sProperties": null,
        "fpolicyProperties": null,
        "saasProperties": null,
        "cbsProperties": null,
        "complianceProperties": null,
        "monitoringProperties": null
    },
    {
        "publicId": "VsaWorkingEnvironment-61kN4p5P",
        "name": "ziv01we03",
        "tenantId": "tenantIDshownhere",
        "svmName": "svm_ziv01we03",
        "creatorUserEmail": "user_email",
        "status": null,
        "awsProperties": null,
        "reservedSize": null,
        "encryptionProperties": null,
        "clusterProperties": null,
        "ontapClusterProperties": null,
        "actionsRequired": null,
        "interClusterLifs": null,
        "cronJobSchedules": null,
        "snapshotPolicies": null,
        "svms": null,
        "activeActions": null,
        "replicationProperties": null,
        "schedules": null,
        "cloudProviderName": "Amazon",
        "isHA": false,
        "workingEnvironmentType": "VSA",
        "supportRegistrationProperties": null,
        "supportRegistrationInformation": [],
        "haProperties": null,
        "capacityFeatures": null,
        "cloudSyncProperties": null,
        "supportedFeatures": null,
        "k8sProperties": null,
        "fpolicyProperties": null,
        "saasProperties": null,
        "cbsProperties": null,
        "complianceProperties": null,
        "monitoringProperties": null
    },
    {
        "publicId": "VsaWorkingEnvironment-E9WanX81",
        "name": "ziv01we04",
        "tenantId": "tenantIDshownhere",
        "svmName": "svm_ziv01we04",
        "creatorUserEmail": "user_email",
        "status": null,
        "awsProperties": null,
        "reservedSize": null,
        "encryptionProperties": null,
        "clusterProperties": null,
        "ontapClusterProperties": null,
        "actionsRequired": null,
        "interClusterLifs": null,
        "cronJobSchedules": null,
        "snapshotPolicies": null,
        "svms": null,
        "activeActions": null,
        "replicationProperties": null,
        "schedules": null,
        "cloudProviderName": "Amazon",
        "isHA": false,
        "workingEnvironmentType": "VSA",
        "supportRegistrationProperties": null,
        "supportRegistrationInformation": [],
        "haProperties": null,
        "capacityFeatures": null,
        "cloudSyncProperties": null,
        "supportedFeatures": null,
        "k8sProperties": null,
        "fpolicyProperties": null,
        "saasProperties": null,
        "cbsProperties": null,
        "complianceProperties": null,
        "monitoringProperties": null
    }
]
----
====

== Get systems for a high availability pair

You can use this workflow to get the system details for a high availability (HA) pair.

=== Step 1. Select the system

Perform the workflow <<Get systems for a single node>> and choose the `publicId` of the required system for the `workingEnvironmentId` path parameter.

=== Step 2. Get the system

You can issue a REST API call to retrieve the systems for an HA pair.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|occm/api/aws/ha/working-environments/<WORKING_ENV_ID>
|===

.Curl example
[source,curl]
curl --request GET \
--location "https://api.bluexp.netapp.com/occm/api/aws/ha/working-environments/<WORKING_ENV_ID>" \
--header "x-agent-id: <AGENT_ID>" \ 
--header "Authorization: Bearer <ACCESS_TOKEN>" \
--header "Content-Type: application/json"


.Additional input parameters

In addition to the parameters common with all REST API calls, the following parameters are also used in the curl example in this step.

[cols="25,25, 25, 45"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|`fields` |Query |No |Identifies the number of fields you will retrieve
|`workingEnvironmentId` <WORKING_ENV_ID> |Path |Yes |Identifies the system ID
|===


.JSON output example
The JSON output example includes an HA Cloud Volumes ONTAP system.

.Example output
[%collapsible]
====
----
{
    "publicId": "VsaWorkingEnvironment-N6BPfglr",
    "name": "ziv04we01ha",
    "tenantId": "tenantIDshownhere",
    "svmName": "svm_ziv04we01ha",
    "creatorUserEmail": "user_email",
    "status": null,
    "awsProperties": null,
    "reservedSize": null,
    "encryptionProperties": null,
    "clusterProperties": null,
    "ontapClusterProperties": null,
    "actionsRequired": null,
    "interClusterLifs": null,
    "cronJobSchedules": null,
    "snapshotPolicies": null,
    "svms": null,
    "activeActions": null,
    "replicationProperties": null,
    "schedules": null,
    "cloudProviderName": "Amazon",
    "isHA": true,
    "workingEnvironmentType": "VSA",
    "supportRegistrationProperties": null,
    "supportRegistrationInformation": [],
    "haProperties": null,
    "capacityFeatures": null,
    "cloudSyncProperties": null,
    "supportedFeatures": null,
    "k8sProperties": null,
    "fpolicyProperties": null,
    "saasProperties": null,
    "cbsProperties": null,
    "complianceProperties": null,
    "monitoringProperties": null
}
----
====
