---
sidebar: sidebar
permalink: cm/wf_common_before.html
keywords: public, cloud, common, workflow, rest, api, BlueXP, console, agent, netapp
summary: 'There are several common workflows you can use with any of the public cloud providers.'
---

= Prepare to use the ONTAP management common API workflows
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
There are several common workflows you can use with any of the public cloud providers or ONTAP on-premises clusters.

[NOTE]
Review the link:overview.html[Get started] section before using any of the REST API workflows.

== Workflow categories
The common workflows are organized into the following functional categories:

Identity and access::
These workflows are typically used to obtain an access token to identify the API caller and manage authorized access to the resources.

SaaS marketplace::
These workflows allow you to manage the subscription of a cloud provider account. You can attach a NetApp Console SaaS subscription to the cloud provider account or retrieve a list of subscriptions.

NetApp Support site::
You can perform specific workflows to manage the NSS keys as part of registering a NetApp Console REST resource for support. Specific NSS keys or all of the available keys can be retrieved. You can also create or delete an NSS key if needed.

Internal task::
You can use these workflows to retrieve the information and status of a background task.

SnapMirror Replication::
These workflows allow you to manage and monitor SnapMirror relationships to replicate data between source and destination systems. This supports disaster recovery and backup which optimizes data availability.

== Console agent setup

You must have a Console agent for the cloud provider or on-premises environment before creating a system and performing other activities using the workflows. You can create a Console agent using the Console web UI. When you create a Console agent, the Console adds the cloud provider account that you deployed the Console agent in to your list of available accounts. Your cloud provider account needs to have the right permissions in order to create a Console agent.

Review https://docs.netapp.com/us-en/occm/concept_connectors.html[Learn about Console agents^] to know how to create and deploy an agent.


