---
sidebar: sidebar
permalink: cm/wf_gcp_cloud_get_wes.html
keywords: cloud, manager, rest, api, list, working, environment, occm
summary: "You can retrieve the Cloud Volumes ONTAP systems that are visible to the user currently signed in."
---

= Get system
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can retrieve the public identifier, system ID, the storage virtual machine name for Cloud Volumes ONTAP systems and other Cloud Volumes ONTAP related details (visible to currently logged in user) which would be used in other workflows.

Choose the workflow to use based on the type of Cloud Volumes ONTAP deployment:

* <<Get a system for a single node, Single Node>>
* <<Get a system for a high availability pair, HA pair>>

== Get a system for a single node
You can use this workflow to retrieve the Cloud Volumes ONTAP system related details for a single node system.

=== 1. Get the systems

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/occm/api/gcp/vsa/working-environments/{workingEnvironmentId}
|===

curl::
[source,curl]
curl --location --request GET 'https://api.bluexp.netapp.com/occm/api/gcp/vsa/working-environments' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input::

(Optional) Query parameters:

*  `fields` string
* `tenantId` string


Output::
The JSON output example includes details of a single node Google Cloud system.

JSON output example::
[source,json]
[
    {
        "publicId": "vsaworkingenvironment-sfrf3wvj",
        "name": "zivgcp01we02",
        "tenantId": "tenantIDshownhere",
        "svmName": "svm_zivgcp01we02",
        "creatorUserEmail": "user_email",
        "status": null,
        "providerProperties": null,
        "reservedSize": null,
        "clusterProperties": null,
        "ontapClusterProperties": null,
        "cloudProviderName": "GCP",
        "snapshotPolicies": null,
        "actionsRequired": null,
        "activeActions": null,
        "replicationProperties": null,
        "schedules": null,
        "svms": null,
        "workingEnvironmentType": "VSA",
        "supportRegistrationProperties": null,
        "supportRegistrationInformation": [],
        "capacityFeatures": null,
        "encryptionProperties": null,
        "supportedFeatures": null,
        "isHA": false,
        "haProperties": null,
        "k8sProperties": null,
        "fpolicyProperties": null,
        "saasProperties": null,
        "cbsProperties": null,
        "complianceProperties": null,
        "monitoringProperties": null
    },
    {
        "publicId": "vsaworkingenvironment-2qkd75xv",
        "name": "zivgcp01we03",
        "tenantId": "tenantIdshownhere",
        "svmName": "svm_zivgcp01we03",
        "creatorUserEmail": "user_email",
        "status": null,
        "providerProperties": null,
        "reservedSize": null,
        "clusterProperties": null,
        "ontapClusterProperties": null,
        "cloudProviderName": "GCP",
        "snapshotPolicies": null,
        "actionsRequired": null,
        "activeActions": null,
        "replicationProperties": null,
        "schedules": null,
        "svms": null,
        "workingEnvironmentType": "VSA",
        "supportRegistrationProperties": null,
        "supportRegistrationInformation": [],
        "capacityFeatures": null,
        "encryptionProperties": null,
        "supportedFeatures": null,
        "isHA": false,
        "haProperties": null,
        "k8sProperties": null,
        "fpolicyProperties": null,
        "saasProperties": null,
        "cbsProperties": null,
        "complianceProperties": null,
        "monitoringProperties": null
    }
]

== Get a system for a high availability pair
You can use this workflow to retrieve the Cloud Volumes ONTAP system related details for an HA system.

=== 1. Get the systems

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/occm/api/gcp/ha/working-environments/{workingEnvironmentId}
|===

curl::
[source,curl]
curl --location --request GET 'https://api.bluexp.netapp.com/occm/api/gcp/ha/working-environments' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input::

(Optional) Query parameters:

*  `fields` string
* `tenantId` string


Output::
The JSON output example includes details of a single node Google Cloud system.

JSON output example::
[source,json]
[
    {
        "publicId": "vsaworkingenvironment-sfrf3wvj",
        "name": "zivgcp01we02",
        "tenantId": "tenantIDshownhere",
        "svmName": "svm_zivgcp01we02",
        "creatorUserEmail": "user_email",
        "status": null,
        "providerProperties": null,
        "reservedSize": null,
        "clusterProperties": null,
        "ontapClusterProperties": null,
        "cloudProviderName": "GCP",
        "snapshotPolicies": null,
        "actionsRequired": null,
        "activeActions": null,
        "replicationProperties": null,
        "schedules": null,
        "svms": null,
        "workingEnvironmentType": "VSA",
        "supportRegistrationProperties": null,
        "supportRegistrationInformation": [],
        "capacityFeatures": null,
        "encryptionProperties": null,
        "supportedFeatures": null,
        "isHA": false,
        "haProperties": null,
        "k8sProperties": null,
        "fpolicyProperties": null,
        "saasProperties": null,
        "cbsProperties": null,
        "complianceProperties": null,
        "monitoringProperties": null
    },
    {
        "publicId": "vsaworkingenvironment-2qkd75xv",
        "name": "zivgcp01we03",
        "tenantId": "tenantIDshownhere",
        "svmName": "svm_zivgcp01we03",
        "creatorUserEmail": "user_email",
        "status": null,
        "providerProperties": null,
        "reservedSize": null,
        "clusterProperties": null,
        "ontapClusterProperties": null,
        "cloudProviderName": "GCP",
        "snapshotPolicies": null,
        "actionsRequired": null,
        "activeActions": null,
        "replicationProperties": null,
        "schedules": null,
        "svms": null,
        "workingEnvironmentType": "VSA",
        "supportRegistrationProperties": null,
        "supportRegistrationInformation": [],
        "capacityFeatures": null,
        "encryptionProperties": null,
        "supportedFeatures": null,
        "isHA": false,
        "haProperties": null,
        "k8sProperties": null,
        "fpolicyProperties": null,
        "saasProperties": null,
        "cbsProperties": null,
        "complianceProperties": null,
        "monitoringProperties": null
    },
    {
        "publicId": "vsaworkingenvironment-lghitaz0",
        "name": "ziv01we01ha",
        "tenantId": "Tenant-kT8tLZay",
        "svmName": "svm_ziv01we01ha",
        "creatorUserEmail": "user_email",
        "status": null,
        "providerProperties": null,
        "reservedSize": null,
        "clusterProperties": null,
        "ontapClusterProperties": null,
        "cloudProviderName": "GCP",
        "snapshotPolicies": null,
        "actionsRequired": null,
        "activeActions": null,
        "replicationProperties": null,
        "schedules": null,
        "svms": null,
        "workingEnvironmentType": "VSA",
        "supportRegistrationProperties": null,
        "supportRegistrationInformation": [],
        "capacityFeatures": null,
        "encryptionProperties": null,
        "supportedFeatures": null,
        "isHA": true,
        "haProperties": null,
        "k8sProperties": null,
        "fpolicyProperties": null,
        "saasProperties": null,
        "cbsProperties": null,
        "complianceProperties": null,
        "monitoringProperties": null
    }
]
