---
sidebar: sidebar
permalink: cm/wf_gcp_cloud_delete_we.html
keywords: cloud, manager, rest, api, working, environment, cloud, volumes, ontap, occm
summary: 'You can delete an existing Cloud Volumes ONTAP system.'
---

= Delete a system
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can delete an existing Google Cloud Cloud Volumes ONTAP system.

Choose the workflow to use based on the type of Cloud Volumes ONTAP deployment:

* <<Delete a system for a single node, Single Node>>
* <<Delete a system for a high availability pair, HA pair>>

== Delete a system for a single node
You can use this workflow to delete a single node system.


=== 1. Select the system

Perform the workflow link:wf_gcp_cloud_get_wes.html#get-a-system-for-a-single-node[Get system] and choose the `publicId` value of the system for the `workingEnvironmentId` path parameter.

=== 2. Delete the system

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|DELETE
|/occm/api/gcp/vsa/working-environments/{workingEnvironmentId}
|===

curl example::
[source,curl]
curl --location --request DELETE 'https://api.bluexp.netapp.com/occm/api/gcp/vsa/working-environments/<WORKING_ENV_ID>' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input::

* Path parameter <WORKING_ENV_ID> `(workingEnvironmentId)` string

* (Optional) Query parameters:

** `localDelete` boolean
+
If `true` the Cloud Volumes ONTAP instance in the cloud is not terminated, but the NetApp Console no longer manages it (default is `false`).
+
If `false` the Cloud Volumes ONTAP instance is deleted including all the cloud resources created for this system.

** `forceDelete` boolean
+
If `true` the system is deleted even if it is part of one or more SnapMirror relationships (default is `false`).

Output::
None

== Delete a system for a high availability pair
You can use this workflow to delete a HA system.


=== 1. Select the system

Perform the workflow link:wf_gcp_cloud_get_wes.html#get-a-system-for-a-high-availability-pair[Get system] and choose the `publicId` value of the system for the `workingEnvironmentId` path parameter.

=== 2. Delete the system

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|DELETE
|/occm/api/gcp/ha/working-environments/{workingEnvironmentId}
|===

curl example::
[source,curl]
curl --location --request DELETE 'https://api.bluexp.netapp.com/occm/api/gcp/ha/working-environments/<WORKING_ENV_ID>' --header 'Content-Type: application/json' --header 'x-agent-id: <AGENT_ID>' --header 'Authorization: Bearer <ACCESS_TOKEN>'

Input::

* Path parameter <WORKING_ENV_ID> `(workingEnvironmentId)` string

* (Optional) Query parameters:

** `localDelete` boolean
+
If `true` the Cloud Volumes ONTAP instance in the cloud is not terminated, but the Console no longer manages it (default is `false`). If `false` the Cloud Volumes ONTAP instance is deleted including all the cloud resources created for this system.

** `forceDelete` boolean
+
If `true` the system is deleted even if it is part of one or more SnapMirror relationships (default is `false`).

Output::

None
