---
sidebar: sidebar
permalink: platform/overview.html
keywords: overview, bluexp, rest, apis, hybrid, multicloud, dat, estate
summary: The NetApp Console enables you to build, protect, and govern your hybrid multicloud data from a single control plane
---

= Learn about the NetApp Console
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The NetApp Console enables you to build, protect, and govern your hybrid multi-cloud data from a single control plane. It is composed of several distinct services, each of which exposes an associated REST API. Collectively these services and APIs form a flexible and extensible development platform you can use to administer your cloud-based and on-premises resources. There are several benefits when using the Console REST APIs.

.Built on REST technology and design principles
The Console APIs have been designed based on REST technology and current best practices. The core technologies include HTTP and JSON.

.Rich set of platform services
The APIs provide access to a rich set of services including storage, cloud, and security. Applications based on the Console platform are robust, resilient, and supportable.

.Access to NetApp console token-based security
The Console authentication and authorization is based on the OAuth2 standard. NetApp relies on the Auth0 service implementation.

.Alignment with the Console web UI
The Console web UI uses the same core REST APIs and so there is consistency between the two access paths.

