---
sidebar: sidebar
api: true
explorer: false
permalink: 'cvo/get-fsx-working-environments-cifs.html'
summary: 'Retrieve CIFS configuration for an FSx system'
---

= Retrieve CIFS configuration for an FSx system

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/fsx/working-environments/{fileSystemId}/cifs`#



Retrieves a CIFS configuration for an existing FSx system.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|fileSystemId
|string
|path
|True
a|

|svm
|string
|query
|False
a|

|===

== Error

```
Status: Default, Default response
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|activeDirectoryDomain
|string
|True
a|Active Directory domain name


|authenticationType
|string
|True
a|Authentication type


|dnsDomain
|string
|True
a|DNS domain name


|ipAddresses
|array[string]
|True
a|DNS server IP addresses


|netBIOS
|string
|True
a|CIFS server NetBIOS name


|organizationalUnit
|string
|True
a|Organizational unit for registration


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "activeDirectoryDomain": "string",
  "authenticationType": "string",
  "dnsDomain": "string",
  "ipAddresses": [
    "string"
  ],
  "netBIOS": "string",
  "organizationalUnit": "string"
}
====

