---
sidebar: sidebar
api: true
explorer: false
permalink: 'cvo/get-onprem-working-environments-cifs.html'
summary: 'Retrieve a CIFS configuration for a system'
---

= Retrieve a CIFS configuration for a system

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/onprem/working-environments/{workingEnvironmentId}/cifs`#



Retrieves CIFS configuration for an existing Cloud Volumes ONTAP system.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|workingEnvironmentId
|string
|path
|True
a|

|vserver
|string
|query
|False
a|

|===

== Error

```
Status: Default, Default response
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|activeDirectoryDomain
|string
|True
a|Active Directory domain name


|authenticationType
|string
|True
a|Authentication type


|dnsDomain
|string
|True
a|DNS domain name


|ipAddresses
|array[string]
|True
a|DNS server IP addresses


|netBIOS
|string
|True
a|CIFS server NetBIOS name


|organizationalUnit
|string
|True
a|Organizational unit for registration


|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "activeDirectoryDomain": "string",
  "authenticationType": "string",
  "dnsDomain": "string",
  "ipAddresses": [
    "string"
  ],
  "netBIOS": "string",
  "organizationalUnit": "string"
}
====

