---
sidebar: sidebar
api: true
explorer: false
permalink: 'cvo/post-gcp-vsa-working-environments-cifs.html'
summary: 'Set up a new CIFS configuration'
---

= Set up a new CIFS configuration
:imagesdir: ../media/

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/gcp/vsa/working-environments/{workingEnvironmentId}/cifs`#



Sets up a new CIFS configuration for an existing Cloud Volumes ONTAP system.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|workingEnvironmentId
|string
|path
|True
a|

|===

== Request Body

                   

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|activeDirectoryDomain
|string
|True
a|Active Directory domain name


|activeDirectoryPassword
|string
|True
a|Active Directory password


|activeDirectoryUsername
|string
|True
a|Active Directory username


|dnsDomain
|string
|False
a|DNS domain name


|ipAddresses
|array[string]
|True
a|DNS server IP addresses


|netBIOS
|string
|True
a|CIFS server NetBIOS name


|organizationalUnit
|string
|True
a|Organizational unit for registration


|svmName
|string
|False
a|SVM name


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "activeDirectoryDomain": "string",
  "activeDirectoryPassword": "string",
  "activeDirectoryUsername": "string",
  "dnsDomain": "string",
  "ipAddresses": [
    "string"
  ],
  "netBIOS": "string",
  "organizationalUnit": "string",
  "svmName": "string"
}
====

== Error

```
Status: Default, Default response
```

