---
sidebar: sidebar
api: true
explorer: false
permalink: 'dw/delete-license-subscriptions-account-subscription-.html'
summary: 'Delete a subscription using the subscription ID (deprecated)'
---

= Delete a subscription using the subscription ID (deprecated)

[.api-doc-operation .api-doc-operation-delete]#DELETE# [.api-doc-code-block]#`/license/subscriptions/account/{accountId}/subscription/{subscriptionId}`#



Deletes or disassociates a subscription that contains the specified subscription ID from an account. A newer version of this deprecated endpoint is available https://docs.netapp.com/us-en/console-automation/dw/delete-license-account-subscription-.html[here.]

The specified subscription must exist and not be associated with a Cloud Volumes ONTAP instance. +
This endpoint deletes the subscription if no other account is associated with the subscription. +
If more than one account is associated with the subscription, this endpoint disassociates the account provided in the `accountId` field and the subscription.

{blank} +
*Token usage:* Either a NetApp Console user token or service token.



CAUTION: This operation is deprecated.

== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|accountId
|string
|path
|True
a|

|subscriptionId
|string
|path
|True
a|

|X-Service-Request-Id
|string
|header
|False
a|Request identifier


|===

== Response

```
Status: 200, Success response
```



== Response

```
Status: 4xx, Error response
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|errorCode
|string
|False
a|Error code


|error
|string
|False
a|Error code/category


|message
|string
|False
a|Error description message


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "errorCode": "string",
  "error": "string",
  "message": "string"
}
====

