---
sidebar: sidebar
api: true
explorer: false
permalink: 'dw/delete-license-subscriptions-account-.html'
summary: 'Delete a subscription using the account ID'
---

= Delete a subscription using the account ID

[.api-doc-operation .api-doc-operation-delete]#DELETE# [.api-doc-code-block]#`/license/subscriptions/account/{accountId}`#



Deletes or disassociates a subscription that contains the specified subscription ID from an account.

The specified subscription must exist and not be associated with a Cloud Volumes ONTAP instance. +
This endpoint deletes the subscription if no other account is associated with the subscription. +
If more than one account is associated with the subscription, this endpoint disassociates the account provided in the `accountId` field and the subscription.

{blank} +
*Token usage:* Either a NetApp Console user token or service token.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|accountId
|string
|path
|True
a|

|X-Service-Request-Id
|string
|header
|False
a|Request identifier


|===

== Request Body

                   

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|subscriptionId
|string
|True
a|

|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "subscriptionId": "string"
}
====

== Response

```
Status: 200, Success response
```



== Response

```
Status: 4xx, Error response
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|errorCode
|string
|False
a|Error code


|error
|string
|False
a|Error code/category


|message
|string
|False
a|Error description message


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "errorCode": "string",
  "error": "string",
  "message": "string"
}
====

