---
sidebar: sidebar
api: true
explorer: false
permalink: 'dw/get-license-data-service-eligibility-account-provider-.html'
summary: 'Retrieve data service eligibility details'
---

= Retrieve data service eligibility details

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/license/data-service-eligibility/account/{accountId}/provider/{cloudProvider}`#



Retrieves data service eligibility details to determine whether an account is eligible to use a data service in an on-premises or cloud environment.

**Note:**

* You can use a user token or service token with scope: license:internal.
* `accountId`, `cloudProvider`, and `service` are required parameters.
* The 'SGWS' value in the cloudProvider parameter denotes that the feature details request is for an on-premises ONTAP system backed up in StorageGRID and retrieves only license details.
* `cloudAccountId` and `cvoId` are optional parameters.
* If the feature details request is for a Cloud Volumes ONTAP or an on-premises ONTAP system backed up on a cloud, you must provide `cloudAccountId`.
* If the feature details request is for Cloud Volumes ONTAP, you must provide the `cvoId` parameter that is used to retrieve the Cloud Volumes ONTAP package.
* The TotalServiceLicensesCapacity value is in TB, the TotalServiceLicensesUsedCapacity value is in TiB, and the FreeTrialEndDate value is in ISO 8601 format.

*Token usage:* Either a NetApp Console user token or service token.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|service
|string
|query
|True
a|

|cloudAccountId
|["string", "null"]
|query
|False
a|

|cvoId
|["string", "null"]
|query
|False
a|

|accountId
|string
|path
|True
a|

|cloudProvider
|string
|path
|True
a|

|X-Service-Request-Id
|string
|header
|False
a|Request identifier


|===

== Response

```
Status: 200, Default Response
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|totalServiceLicensesCapacity
|integer
|False
a|

|totalServiceLicensesUsedCapacity
|number
|False
a|

|subscriptionDetails
|link:#subscriptionDetails[subscriptionDetails]
|False
a|

|freeTrialEndDate
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "subscriptionDetails": {
    "subscriptionId": "string"
  },
  "freeTrialEndDate": "string"
}
====

== Response

```
Status: 4xx, Error response
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|errorCode
|string
|False
a|Error code


|error
|string
|False
a|Error code/category


|message
|string
|False
a|Error description message


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "errorCode": "string",
  "error": "string",
  "message": "string"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#subscriptionDetails]
[.api-collapsible-fifth-title]
subscriptionDetails

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|subscriptionId
|string
|False
a|

|active
|boolean
|False
a|

|===


//end collapsible .Definitions block
====
