---
sidebar: sidebar
api: true
explorer: false
permalink: 'dw/subscription_overview.html'
summary: 'Subscription endpoints in the License and subscriptions REST API for the NetApp Console'
---

= Subscription endpoints in the License and subscriptions REST API for the NetApp Console



The subscription endpoints manage the subscriptions to NetApp Console services for end users. +
The endpoints register a specified subscription with the Console and associate it with the identity and access management service.

A subscription for the Console services is a collection of the following:

* Subscription ID (such as 666777, A-S000003969)
* Subscription type (such as Keystone)
* Expiration date (such as 20251109)
* Last modified (such as 2021-11-09 00:00:00)
* Resource identifier (such as license-481000495-6897991f-f83f-41c1-b151-eb62073e57be), used internally

The subscription endpoints support the Create-Read-Update-Delete (CRUD) operation on the `subscription` and `subscription_resource` tables based on the subscription ID.

Each license or subscription that is managed by the Console has a resource identifier in the identity and access management service that associates it with an account.

You can perform the following actions with the subscription endpoints:

* Read, create, update, or delete a subscription.


