---
sidebar: sidebar
api: true
explorer: false
permalink: 'tenancy/workspace_overview.html'
summary: 'Workspace endpoints in the Accounts REST API'
---

= Workspace endpoints in the Accounts REST API



+++<fieldset>+++The workspace endpoints provide more granular access control within a given account. An account can have one or more workspaces, although a specific workspace can only be owned by one account.

Each workspace is defined through the following configuration information:

* Name as selected by the administrator
* Unique identifier generated by the system at creation
* Identifier of the owning account
* One or more users allowed to operate within the workspace
* One or more Connectors
* One or more resources

Limiting which users can operate within a workspace, along with the set of Connectors and resources defined for the workspace, provides a natural way to enforce access control. Additional access restrictions can be defined for the Connectors and resources within the workspace.

Workspaces enable enhanced access control granularity by isolating resources. For example, company departments or projects can be assigned to different workspaces. This isolation provides a high level of security.

The following actions can be performed with the workspace endpoints:

* Create a workspace
* List the workspaces within an account
* Add a user to a workspace
* Remove a user from a workspace
* List the workspaces associated with a user
* Delete a workspace
* Rename a workspace
* Add a Connector to a workspace
* Remove a Connector from a workspace
* List the Connectors associated with a workspace+++</fieldset>+++


