---
sidebar: sidebar
api: true
explorer: false
permalink: 'ipa/license_overview.html'
summary: 'License endpoints in the In-Product Automation REST API for the NetApp Console'
---

= License endpoints in the In-Product Automation REST API for the NetApp Console



The license endpoints in the IPA service provide license management to the IPA. License management includes license registration, deregistration, and status checks to the NetApp-wide IPA.

The registration and deregistration API endpoints register and deregister the NetApp Console license to the IPA service. +
Based on the various versions of the IPA service, there are several versions of the NetApp Console license registration and deregistration endpoints.

Similarly, the license status check endpoint has different versions that relate to different IPA service versions.

The following describes the mapping between the NetApp Console IPA licensing endpoints and the IPA product registration endpoints:

* Registration and deregistration maps to+++<ipaendpoint>+++/IPA/v2/prodregister+++</ipaendpoint>+++
* Status check maps to+++<ipaendpoint>+++/IPA/v2/prodstatus+++</ipaendpoint>+++
* IPA version-5 (IPA v5) status maps to+++<ipaendpoint>+++/entitlement/IPA/v4/prodstatus+++</ipaendpoint>+++
* IPA v5 authentication maps to+++<ipaendpoint>+++/entitlement/IPA/v4/authenticate+++</ipaendpoint>+++
* IPA v6 status maps to+++<ipaendpoint>+++/entitlement/IPA/v6/prodstatus+++</ipaendpoint>+++

For the credentials required for license management, the license endpoints map to cred_service_endpoint/accounts/:accountId/credentials.

You can perform the following operations by using IPA license endpoints across various versions of the IPA service:

* Registration
* Deregistration
* Registration status check


